
(function() {
    'use strict';
    angular
        .module('minotaur')
        .constant('MMS_GET_COMPONENT', 'MMS/getComponents/')
        .constant('MMS_GET_COMPONENT_ACADEMICS', 'StudentAcademics/getComponents/')
        .constant('MMS_INSERT_COMPONENT', 'MMS/insertComponent/')
        .constant('MMS_SURVEY_PO_WISE_REPORT', 'StudentMMS/survey_po_wise_Report/')
        .constant('MMS_MULTI_SUBJECT', 'StudentMMS/add_bonus_rule/')
        .constant('MMS_SBRULE', 'StudentMMS/add_subrule/')
        .constant('MMS_BLOOM_TAXONOMY', 'StudentMMS/bloomtaxonomy/')
        .constant('MMS_UVECOORDINATOR', 'StudentMMS/uveCoordinator/')
        .constant('MMS_SURVEY_ADD_QUESTION', 'StudentMMS/survey_add_Question/')
        .constant('MMS_Student_NOMINAL', 'StudentAcademics/StudentNominalList/')
        .constant('MMS_Student_ADD_QUES', 'StudentMMS/AddQues/')
        .constant('ACAD_GET_DEPT', 'StudentAcademics/getComponents/')
        .constant('ACAD_GET_SUBJECT_TYPE','StudentAcademics/getComponents/')
        .constant('ACAD_GET_COURSE', 'StudentAcademics/StudentNominalList/')
        .constant('MMS_VISION', 'StudentMMS/mms_vision/')
	    .constant('MMS_VISION', 'StudentMMS/mms_vision/')
	    .constant('MMS_SEM_MULTI', 'StudentAcademics/DailyAttCountReport/')
        .constant('MMS_QUESTION_PAPER', 'StudentMMS/quespaper_format/')
        .constant('MMS_CREATE_QP', 'StudentMMS/create_question_paper/')
        .constant('MMS_APPROVE_QUESTION_PAPER', 'StudentMMS/approve_question_paper/')
        .constant('DAILY_ATT_COUNT_REPORT','StudentAcademics/DailyAttCountReport/')
        .constant('MMS_PEO_MI_MAPPING','StudentMMS/peo_mi_mapping/')
        .constant('MMS_PO_PEO_MAPPING','StudentMMS/po_peo_mapping/')
        .constant('MMS_SET_CO_DETAILS','StudentMMS/Set_CO_details/')
        .constant('MMS_CO_PO_MAPPING','StudentMMS/co_po_mapping/')
        .constant('MMS_QUESTION_MODERATOR','StudentMMS/QuestionModerator/')
        .constant('MMS_STUDENT_INTERNAL_MARKS','StudentMMS/student_internal_marks/')
        .constant('MMS_ATTENDANCE_MARKS','StudentMMS/mms_attendance_marks/')
        .constant('MMS_BONUS_MARKS_RULE' , 'StudentMMS/bonus_marks_rule/')
        .constant('MMS_CT_WISE_MARKS','StudentMMS/ct_wise_subjects_marks/')
        .constant('MMS_CT_WISE_MARKS_FACULTY','StudentMMS/ct_wise_subjects_marks_faculty/')
        .constant('MMS_CT_MARKS_REPORT','StudentMMS/ct_marks_report/')
        .constant('MMS_COE_COORDINATOR','StudentMMS/CoeCoordinator/')
        .constant('MMS_EXAM_SCHEDULE','StudentMMS/mms_exam_schedule_form/')
        .constant('MMS_ENTER_INTERNAL_MARKS','StudentMMS/mms_exam_schedule_form/')
        .constant('MMS_CT_MARKS_RULE','StudentMMS/CtMarksRule/')
        .constant('MMS_GET_STUDENT_TA_MARKS' , 'StudentMMS/enter_ta_marks/')
        .constant('MMS_STUDENT_MARKSHEET','StudentMMS/student_marksheet/')
        .constant('CT_WISE_MARKS','StudentMMS/ct_wise_question_marks/')
        .constant('STUDENT_CO_REPORT','StudentMMS/mms_student_co_report/')
        .constant('STUDENT_CO_REPORT_INTERNAL','StudentMMS/mms_student_internal_co_report/')
        .constant('ATTAINMENT_SETTINGS','StudentMMS/mms_attainment_settings/')
        .constant('ENTER_ASSI_QUIZ_MARKS','StudentMMS/enter_assi_quiz_marks/')
        .constant('COURSE_OVERALL_ATTAINMENT','StudentMMS/course_overall_attainment/')
        .constant('GET_OVERALL_PO_ATTAINMENT','StudentMMS/get_course_overall_po_attainment/')
        .constant('PO_ATTAINMENT_GAP_REPORT','StudentMMS/po_attainment_gap_report/')
        .constant('CO_PO_TARGET_REPORT','StudentMMS/co_po_target_report/')
        .constant('ALL_SURVEY_PO_WISE_REPORT','StudentMMS/all_survey_po_wise_Report/')
        .constant('PO_PEO_ATTAINMENT_REPORT','StudentMMS/po_peo_attainment_report/')
        .constant('PEO_MI_ATTAINMENT_REPORT','StudentMMS/peo_mi_attainment_report/')
        .constant('CO_PO_MATRIX','StudentMMS/co_po_matrix/')
        .constant('ADD_SUBRULE_BONUS_MARKS','StudentMMS/add_subrule/')
        .constant('GENERATE_BONUS_MARKS','Store_data/store_bonus_marks/')
        // .constant('PEO_MI_ATTAINMENT_REPORT','StudentMMS/get_course_overall_po_attainment/')
})();
